# Generated by Django 5.1.5 on 2025-01-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='state',
            name='abbr',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
