# Generated by Django 5.1.5 on 2025-01-23 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_country_options_state_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='location.country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
    ]
