# Generated by Django 5.1.5 on 2025-01-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_state_country_alter_state_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'managed': False},
        ),
    ]
