# Generated by Django 5.1.5 on 2025-01-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_state_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='state',
            table='states',
        ),
    ]
